version: "3" 
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySQLRootPassword
      MYSQL_DATABASE: MySQLDatabaseName
      MYSQL_USER: MySQLUsername
      MYSQL_PASSWORD: MySQLUserPassword
 
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MySQLUsername           # ✅ Match MYSQL_USER
      WORDPRESS_DB_PASSWORD: MySQLUserPassword   # ✅ Match MYSQL_PASSWORD
      WORDPRESS_DB_NAME: MySQLDatabaseName       # ✅ Match MYSQL_DATABASE
    volumes:
      - "./:/var/www/html"
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root                             # ✅ Use root or MySQLUsername
      PMA_PASSWORD: MySQLRootPassword            # ✅ Use the correct password for that user
 
volumes:
  mysql: {}