version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MySQLRootPassword
      MYSQL_DATABASE: MySQLDatabaseName
      MYSQL_USER: MySQLUsername
      MYSQL_PASSWORD: MySQLUserPassword
    volumes:
      - mysql_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MySQLUsername
      WORDPRESS_DB_PASSWORD: MySQLUserPassword
      WORDPRESS_DB_NAME: MySQLDatabaseName
    volumes:
      - ./wordpress:/var/www/html
    command: >
      sh -c "
        chown -R www-data:www-data /var/www/html &&
        chmod -R 755 /var/www/html &&
        if [ -f /var/www/html/wp-config.php ] && ! grep -q 'FS_METHOD' /var/www/html/wp-config.php; then
          echo \"define('FS_METHOD', 'direct');\" >> /var/www/html/wp-config.php;
        fi &&
        docker-entrypoint.sh apache2-foreground
      "

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: MySQLRootPassword

volumes:
  mysql_data:
